[package]
name = "configuration-rs"
version = "0.1.0"
authors = ["Radosław Kot <rdkt13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1" }
futures = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }

# use feature flags for those
serde_json = { version = "1.0" }
serde_yaml = { version = "0.8" }

[dev-dependencies]
rstest = { version = "0.6.4" }